name: "ROCm CI"

on: [push, pull_request]

jobs:
  rocm-ci:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build & Test
      run: |
        .pfnci/linux/run.sh rocm-6-1 build test
